
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: lighthouse-service-vpc
  
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1b
      VpcId:
        Ref: VPC
  
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.2.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: us-east-1a
      VpcId:
        Ref: VPC

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn:
      - VPC
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway

  VPCGatewayAttatchment:
    Type: AWS::EC2::VPCGatewayAttachment
    DependsOn:
      - VPC
      - InternetGateway
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn:
      - VPC
      - VPCGatewayAttatchment
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: PublicRouteTable
  
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn:
      - PublicRouteTable
      - InternetGateway
      - VPCGatewayAttatchment
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId:
        Ref: PublicRouteTable
      GatewayId:
        Ref: InternetGateway

  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - PublicRouteTable
      - PublicSubnetA
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetA

  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn:
      - PublicRouteTable
      - PublicSubnetB
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      SubnetId:
        Ref: PublicSubnetB

  AuditQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: LighthouseAuditQueue
      VisibilityTimeout: 60
  
  # Provides Access to Required AWS Resources
  InstanceRole:
    Type: AWS::IAM::Role
    DependsOn:
      - AuditQueue
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      Policies:
        - PolicyName: AuditQueueAccess
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: sqs:*
                Resource:
                  Fn::GetAtt:
                    - AuditQueue
                    - Arn
        - PolicyName: EC2DescribeTagsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: ec2:DescribeTags
                Resource: '*'
        - PolicyName: AutoScalingGroupPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - autoscaling:SetInstanceProtection
                  - autoscaling:SetInstanceHealth
                Resource: '*'
        - PolicyName: LogsPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: arn:aws:logs:*:*:*
  
  # Binds Instance with Instance Role
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn:
      - InstanceRole
    Properties:
      Path: /
      Roles:
        - Ref: InstanceRole
  
  # Creates Template for Instances
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    DependsOn:
      - InstanceProfile
    Properties:
      LaunchTemplateData:
        ImageId: ami-047a51fa27710816e
        InstanceType: m5.large
        TagSpecifications:
          - ResourceType: instance
            Tags:
            - Key: Name
              Value:
                Ref: AWS::StackName
        IamInstanceProfile:
          Arn:
            Fn::GetAtt:
              - InstanceProfile
              - Arn
        UserData:
          Fn::Base64:
            Fn::Sub: '#!/bin/bash

            yum -y install git jq

            cd /root && git clone https://github.com/gkemp94/lighthouse.git

            REGION=${AWS::Region} SQSQUEUE=${AuditQueue} CLOUDWATCHLOGSGROUP=${CloudwatchLogs}
            bash /root/lighthouse/scripts/start.sh
            '
  
  AutoScalingServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: autoscaling.amazonaws.com
      
  EC2FleetServiceLinkedRole:
    Type: AWS::IAM::ServiceLinkedRole
    Properties:
      AWSServiceName: ec2fleet.amazonaws.com

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    DependsOn:
      - LaunchTemplate
      - AutoScalingServiceLinkedRole
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
    Properties:
      DesiredCapacity: 1
      MinSize: 1
      MaxSize: 1
      HealthCheckType: EC2
      MixedInstancesPolicy:
        InstancesDistribution:
          OnDemandBaseCapacity: 0
          OnDemandPercentageAboveBaseCapacity: 0
          SpotAllocationStrategy: capacity-optimized
        LaunchTemplate:
          LaunchTemplateSpecification:
            LaunchTemplateId:
              Ref: LaunchTemplate
            Version:
              Fn::GetAtt:
                - LaunchTemplate
                - LatestVersionNumber
      VPCZoneIdentifier:
        - Ref: PublicSubnetA
        - Ref: PublicSubnetB
  
  AutoScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    DependsOn:
      - AutoScalingGroup
      - AuditQueue
    Properties:
      AutoScalingGroupName:
        Ref: AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        CustomizedMetricSpecification:
          Dimensions:
            - Name: QueueName
              Value:
                Fn::GetAtt:
                  - AuditQueue
                  - QueueName
          MetricName: ApproximateNumberOfMessagesVisible
          Namespace: AWS/SQS
          Statistic: Sum
          Unit: Count
        TargetValue: .85

  CloudwatchLogs:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 7
    